### ISSUE TITLE
Lava uses

### ISSUE THREAD

**Issue by DatOnePlayer** [JerichoFletcher/mechanical-warfare#25]
Is lava uses only for creating stone? Could've need more uses like as ammunition for wave turrets (or maybe your own version of liquid turret) and also same like slags (can be output into certain items via separators or even specialised separator)

**Comment by JerichoFletcher** [comment]
> as ammunition for wave turrets

Yes, that's actually already implemented since v1.1 release. We also plan to add a new defensive block that only accepts lava as input on the upcoming v1.5 though.

> maybe your own version of liquid turret

_lmao yes ofc_
Good suggestion though. We'll consider adding a new stronger liquid turret on the next update.

> can be output into certain items via separators or even specialised separator

We might add a separator for lava. Not sure yet.
